[212.520s] Invoking command in '/home/ubuntu/ros2_ws/src/raspimouse': PYTHONPATH=/home/ubuntu/ros2_ws/install/raspimouse_ros2/lib/python3.8/site-packages:${PYTHONPATH} /usr/bin/python3 setup.py egg_info --egg-base ../../build/raspimouse_ros2 build --build-base /home/ubuntu/ros2_ws/build/raspimouse_ros2/build install --prefix /home/ubuntu/ros2_ws/install/raspimouse_ros2 --record /home/ubuntu/ros2_ws/build/raspimouse_ros2/install.log --single-version-externally-managed
[930.540s] Traceback (most recent call last):
[930.758s]   File "<frozen importlib._bootstrap_external>", line 148, in _path_is_mode_type
[931.332s]   File "<frozen importlib._bootstrap_external>", line 142, in _path_stat
[931.335s] FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.8/urllib/__init__.so'
[931.337s] 
[931.339s] During handling of the above exception, another exception occurred:
[931.340s] 
[931.341s] Traceback (most recent call last):
[931.343s]   File "setup.py", line 1, in <module>
[931.362s]     from setuptools import setup
[931.366s]   File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 17, in <module>
[931.461s]     import setuptools.version
[931.463s]   File "/usr/lib/python3/dist-packages/setuptools/version.py", line 1, in <module>
[931.494s]     import pkg_resources
[931.546s]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 36, in <module>
[931.646s]     import email.parser
[931.648s]   File "/usr/lib/python3.8/email/parser.py", line 12, in <module>
[931.747s]     from email.feedparser import FeedParser, BytesFeedParser
[931.750s]   File "/usr/lib/python3.8/email/feedparser.py", line 27, in <module>
[931.780s]     from email._policybase import compat32
[931.782s]   File "/usr/lib/python3.8/email/_policybase.py", line 9, in <module>
[931.800s]     from email.utils import _has_surrogates
[931.801s]   File "/usr/lib/python3.8/email/utils.py", line 31, in <module>
[931.855s]     import urllib.parse
[931.862s]   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[931.865s]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
[931.870s]   File "<frozen importlib._bootstrap>", line 914, in _find_spec
[931.875s]   File "<frozen importlib._bootstrap_external>", line 1407, in find_spec
[931.877s]   File "<frozen importlib._bootstrap_external>", line 1379, in _get_spec
[931.879s]   File "<frozen importlib._bootstrap_external>", line 1525, in find_spec
[931.883s]   File "<frozen importlib._bootstrap_external>", line 156, in _path_isfile
[931.886s]   File "<frozen importlib._bootstrap_external>", line 148, in _path_is_mode_type
[931.888s] KeyboardInterrupt
[931.984s] Invoked command in '/home/ubuntu/ros2_ws/src/raspimouse' returned '-2': PYTHONPATH=/home/ubuntu/ros2_ws/install/raspimouse_ros2/lib/python3.8/site-packages:${PYTHONPATH} /usr/bin/python3 setup.py egg_info --egg-base ../../build/raspimouse_ros2 build --build-base /home/ubuntu/ros2_ws/build/raspimouse_ros2/build install --prefix /home/ubuntu/ros2_ws/install/raspimouse_ros2 --record /home/ubuntu/ros2_ws/build/raspimouse_ros2/install.log --single-version-externally-managed
